### ISSUE TITLE
P#62389 #2781085 address list without of a name created in WP-plugin

### ISSUE THREAD

**Issue by michaelarnold-dev** [onOfficeGmbH/oo-wp-plugin#161]
Tested in v2.20.12-1-gb936a28e on https://wpptest.onofficeweb.com 

Addresses -> An address list without a name exists. How could it be created?

**Comment by michaelarnold-dev** [comment]
@nglelinh : Do you have an idea how that can be fixed?

**Comment by michaelarnold-dev** [comment]
@nglelinh Any update here?

**Comment by nglelinh** [comment]
@michaelarnold-dev we did not check this issue yet

**Comment by vu-vuong-esg** [comment]
@michaelarnold-dev , i re produce issue with video, is that issue you are referring to?

https://user-images.githubusercontent.com/72490437/149263979-a2120e20-cc58-43d0-bc74-e767b8fdfe17.mp4

**Comment by michaelarnold-dev** [comment]
The tester says that the following video shows the issue:
https://user-images.githubusercontent.com/77264788/149886476-5c2c0ca3-ca3b-483e-81da-89572cd47b9a.mp4

**Comment by vu-vuong-esg** [comment]
i will fix it

**Comment by michaelarnold-dev** [comment]
@vu-vuong-esg Is the fixing process still in progress?

**Comment by tang-hien-egs** [comment]
> @vu-vuong-esg Is the fixing process still in progress?

i fixed done, can you check PR https://github.com/onOfficeGmbH/oo-wp-plugin/pull/172
