### ISSUE TITLE
P#62393 #2781085 Error in contact form

### ISSUE THREAD

**Issue by michaelarnold-dev** [onOfficeGmbH/oo-wp-plugin#162]
Tested in v2.20.12-1-gb936a28e on https://wpptest.onofficeweb.com 

Contact form -> Contact form page "Contact form" (02/26/2021 at 2:05 PM) has Uncaught TypeError, see below. Cause or field configuration unknown.
```
Fatal error: Uncaught TypeError: 
Argument 1 passed to onOffice\WPlugin\Types\FieldsCollection::containsFieldByModule() must be of the type string, null given, 
called in /www/htdocs/w01b9fbd/wpptest.onofficeweb.com/htdocs/wp-content/plugins/onoffice/plugin/Form.php on line 216 
and defined in /www/htdocs/w01b9fbd/wpptest.onofficeweb.com/htdocs/wp-content/plugins/onoffice/plugin/Types/FieldsCollection.php:65 

Stack trace: 
#0 /www/htdocs/w01b9fbd/wpptest.onofficeweb.com/htdocs/wp-content/plugins/onoffice/plugin/Form.php(216): 
 onOffice\WPlugin\Types\FieldsCollection->containsFieldByModule(NULL, 'message') 
#1 /www/htdocs/w01b9fbd/wpptest.onofficeweb.com/htdocs/wp-content/plugins/onoffice/plugin/Form.php(199):
 onOffice\WPlugin\Form->filterActiveInputFields(Array) 
#2 /www/htdocs/w01b9fbd/wpptest.onofficeweb.com/htdocs/wp-content/plugins/onoffice/templates.dist/form/defaultform.php(52):
 onOffice\WPlugin\Form->getInputFields() 
#3 /www/htdocs/w01b9fbd/wpptest.onofficeweb.com/htdocs/wp-content/plugins/onoffice/plugin/Template.php(118)
 in /www/htdocs/w01b9fbd/wpptest.onofficeweb.com/htdocs/wp-content/plugins/onoffice/plugin/Types/FieldsCollection.php on line 65
```
There was a critical error on your website. Please check the inbox of your website administrator email address for further instructions.

**Comment by michaelarnold-dev** [comment]
@nglelinh Could you or your colleagues already reproduce that error?

**Comment by hungnc89** [comment]
> @nglelinh Could you or your colleagues already reproduce that error?

Hi @michaelarnold-dev did you mean contact form on the link https://wpptest.onofficeweb.com/hallo-welt/ has error ?

![image](https://user-images.githubusercontent.com/72601287/148878183-cf6a4058-9d01-46cd-b647-70836b8e3f41.png)

I don't see anything like error on website.

**Comment by michaelarnold-dev** [comment]
Hi @nglelinh , Robert says that if you cannot fi the error with help of the error code then the issue can be closed
