### ISSUE TITLE
P#62397 #2781085 interest form -> property type not selectable

### ISSUE THREAD

**Issue by michaelarnold-dev** [onOfficeGmbH/oo-wp-plugin#163]
Tested in v2.20.12-1-gb936a28e on https://wpptest.onofficeweb.com 

Interest form -> frontend: Property type cannot be selected, empty selection. Dependency to real estate type not working?

**Comment by hungnc89** [comment]
![image](https://user-images.githubusercontent.com/72601287/148537781-a4cfc7eb-54be-46bd-b232-20c6414a618b.png)
![image](https://user-images.githubusercontent.com/72601287/148537802-73ccbb12-4dc8-4144-a821-c4def4ac83f0.png)
@michaelarnold-dev I tested on master branch and didn't get this bug

**Comment by michaelarnold-dev** [comment]
That bug doesn't exist anymore.
