### ISSUE TITLE
P#69481 Remove redundant "Show Estate Status" checkbox

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOfficeGmbH/oo-wp-plugin#202]
# Current state

The checkbox labeled "Show Estate Status" appears twice in the settings for estate lists. This was introduced in version 2.21.7.
![grafik](https://user-images.githubusercontent.com/90763364/162232556-d561c92c-c665-47f1-8159-6937aff4c6d4.png)

# Desired state

"Show Estate Status" should only appear in the "Layout & Design" box.
![grafik](https://user-images.githubusercontent.com/90763364/162232618-dfb9315a-533a-45f1-a981-261cc8ef5ea7.png)

**Comment by jmaas-onoffice** [comment]
@nglelinh This is a small change to test out the new process. Feel free to also give feedback on the process. ;)

**Comment by nglelinh** [comment]
@jmaas-onoffice Thank you, sure we will improve it together

**Comment by jmaas-onoffice** [comment]
@nglelinh After you've created a PR, could you link the issue? To the right is a "Development" section where you can do so.
