### ISSUE TITLE
P#71173 Make CSS local to templates

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOfficeGmbH/oo-wp-plugin#235]
# Current state
Changes to the CSS files (especially [`onoffice_defaultview.css`](https://github.com/onOfficeGmbH/oo-wp-plugin/blob/5109fa67edaa2256f2ed5357d503ba3009ea32b5/css/onoffice_defaultview.css)) can break personalized templates. Since `onoffice_defaultview.css` also gets loaded for personalized templates, users may rely on it. If we change it, we can only test it with the default templates, so it could break users' templates.

This means we do not want to touch those CSS files and cannot make improvements to the included templates.

# Desired state
1. The CSS should be coupled to the templates. We can achieve this by loading a CSS file from the templates folder. That path should be `templates/onoffice-style.css`. (This allows users to copy the CSS alongside the templates. We can then change the included CSS, because it will not affect the copied CSS file.)

    The possible paths:
    - Included: `wp-content/plugins/onoffice-for-wp-websites/templates.dist/onoffice-style.css`
    - Plugin folder: `wp-content/plugins/onoffice-personalized/templates/onoffice-style.css`
    - Theme folder: `wp-content/themes/<theme>/onoffice-theme/templates/onoffice-style.css`

2. The change should be backwards compatible, so that users can keep their existing templates without changes.

    We use the existing template folder hierarchy (theme, then plugin, then included). Look in the highest existing template folder. If there is a `onoffice-style.css`, use it. Otherwise use the old `onoffice_defaultview.css`.
  
    Cases:
    - If there is a theme folder:
      - If it contains a `onoffice-style.css`, use that.
      - If it does not contain a `onoffice-style.css`, use the old `onoffice_defaultview.css`.
    - Else, if there is a plugin folder:
      - If it contains a `onoffice-style.css`, use that.
      - If it does not contain a `onoffice-style.css`, use the old `onoffice_defaultview.css`.
    - Else (there are only the included templates):
      - Use the included `wp-content/plugins/onoffice-for-wp-websites/templates.dist/onoffice-style.css`.

**Comment by LongTrong-exe** [comment]
@jmaas-onoffice Your examples is so confusing :confused::cry:
