### ISSUE TITLE
Geo-Position field in Interest forms

### ISSUE THREAD

**Issue by fredericalpers** [onOfficeGmbH/oo-wp-plugin#757]
# Initiative
Enhance user control in the onOffice for WP-Websites plugin

### Epic
Customizable placement of geo-position field in interest forms

### User Story
As a real estate agent utilizing thje onOffice for WP-Websites plugin, I often configure interest forms to capture specific search criteria from potential clients. Currently, the geo-position field is consistently displayed at the last position within the search criteria section, regardless of any sorting adjustments made in the plugin backend. To improve the customization options and streamline the form-building process, I propose implementing functionality that allows me to specify the placement of the geo-position field according to my preferences.

The static placement of the geo-position field limits my ability to organize the interest form effectively and may not align with the layout I intend to create. By  enabling the customizable placement of this field, I can tailor the form layout to suit various requirements and optimize the user experience for potential clients.

### Tasks

- [x] Develop the functionality to enable users to customize the placement of the geo position field within the search criteria section
- [x] Ensure that changes to the placement of the geo-position field are accurately reflected in the frontend of the interest form

By implementing this feature, the onOffice for WP-Websites plugin will empower real estate agents to create more tailored and user-friendly interest forms, ultimately enhancing their ability to capture relevant information from potential clients.

![geoposition-fehler](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/4024a543-92c8-4fd6-85cd-bc862154fabd)

**Comment by yeneastgate** [comment]
@fredericalpers During implementation, I found that the "geo-position" field is consistently displayed at the last position within the search criteria section, regardless of any sorting adjustments made in the plugin backend in 3 screens: estate list page, applicant search form, and interest form.
However, I see that your requirement only mentions fixing the bug in the "interest form."
Do you want me to update all other screens (estate list page and applicant search form)?

Please watch my video demo on the "interest form": https://files.fm/u/zepwvugcf8#/view/5m9y9g76nc

**Comment by fredericalpers** [comment]
> @fredericalpers During implementation, I found that the "geo-position" field is consistently displayed at the last position within the search criteria section, regardless of any sorting adjustments made in the plugin backend in 3 screens: estate list page, applicant search form, and interest form. However, I see that your requirement only mentions fixing the bug in the "interest form." Do you want me to update all other screens (estate list page and applicant search form)?
> 
> Please watch my video demo on the "interest form": https://files.fm/u/zepwvugcf8#/view/5m9y9g76nc

please go ahead and also fix it for all of the mentioned screens, thank you :)

**Comment by yeneastgate** [comment]
@fredericalpers Ok, I got it

**Comment by yeneastgate** [comment]
@fredericalpers I have implemented it and this is demo video: https://files.fm/u/8j9hv72h8d#/view/7n5byzybut
Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
> @fredericalpers I have implemented it and this is demo video: https://files.fm/u/8j9hv72h8d#/view/7n5byzybut Please check and let me know your opinion. Thanks!

looks good to me, thank you! :)
